[package]
name = "crane-lex"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
nom = "7.1.3"
nom_locate = "4.1.0"
crane-macros = { path = '../crane-macros/' }
